name:                terminaion-checker
version:             0.1.0.0
github:              "ksrky/terminaion-checker"
license:             BSD-3-Clause
author:              "Rikiya Kashiwagi"
maintainer:          "kswgrky@gmail.com"
copyright:           "Copyright (c) 2025 Rikiya Kashiwagi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ksrky/terminaion-checker#readme>

language:            GHC2021

dependencies:
- array
- base >= 4.7 && < 5
- containers
- lens
- logict
- mtl
- sbv
- template-haskell
- text
- transformers

default-extensions:
- FunctionalDependencies
- ImportQualifiedPost
- LambdaCase
- ImportQualifiedPost

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  terminaion-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminaion-checker

tests:
  terminaion-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - terminaion-checker
    - hspec
